
services:
  alloy:
    image: grafana/alloy:latest
    ports:
      - "4317:4317"   # OTLP gRPC in
      - "4318:4318"   # OTLP HTTP in (optional)
      - "12345:12345" # Alloy UI (optional)
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy:ro
