version: "3.8"

services:
  alloy:
    image: grafana/alloy:latest
    ports:
      - "4317:4317" # OTLP gRPC endpoint for traces/metrics/logs
      - "4318:4318" # OTLP HTTP endpoint
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy
    command: ["run", "/etc/alloy/config.alloy"]
    restart: always

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
      - tempo
      - mimir
    restart: always

  loki:
    image: grafana/loki:2.9.3
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo:2.5.0
    ports:
      - "3200:3200"
    command: ["-config.file=/etc/tempo.yaml"]

  mimir:
    image: grafana/mimir:2.13.0
    ports:
      - "9009:9009"
    command: ["-ingester.client.grpc-address=127.0.0.1:9095"]
